name: Unity Game Automatic Build - Multi OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo GitHub Token
        run: echo "${{ secrets.GITHUB_TOKEN }}"


      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        env:
          unity_license: ${{ secrets.UNITY_LICENSE }}
          unity_email: ${{ secrets.UNITY_EMAIL }}
          unity_password: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          testMode: editMode
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          containerRegistryRepository: unityci/webgl-tests


      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        env:
          unity_license: ${{ secrets.UNITY_LICENSE }}
          unity_email: ${{ secrets.UNITY_EMAIL }}
          unity_password: ${{ secrets.UNITY_PASSWORD }}
        with:
          customImage: unityci/editor:2022.3.4f1-base-0
          targetPlatform: WebGL
          projectPath: .
          buildsPath: build/${{ matrix.os }}
          containerRegistryRepository: unityci/webgl-tests

      - name: Upload WebGL Build
        uses: actions/upload-artifact@v4
        with:
          name: WebGL-Build-${{ matrix.os }}
          path: build/${{ matrix.os }}
