name: Unity Game Automatic Build - Multi OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Unity
        uses: game-ci/unity-setup@v4
        with:
          unityVersion: 2022.3.5f1

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        with:
          projectPath: 2D_Shooter
          testMode: editmode

      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: WebGL
          projectPath: 2D_Shooter
          buildsPath: build/${{ matrix.os }}

      - name: Upload WebGL Build
        uses: actions/upload-artifact@v4
        with:
          name: WebGL-Build-${{ matrix.os }}
          path: build/${{ matrix.os }}
